version: '3.1'

services:
  wordpress:
    image: wordpress
    container_name: ecomm_wp
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: rootpass

  phpmyadmin:
    image: phpmyadmin
    container_name: ecomm_phpmyadmin
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  wordpress:
